-- 1. Enable pgvector extension (for future semantic search)
create extension if not exists vector;

-- 2. Create the memories table
create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  user_id text not null,
  role text not null check (role in ('user', 'assistant', 'system', 'tool')),
  content text not null,
  metadata jsonb default '{}'::jsonb,
  created_at timestamp with time zone default now()
);

-- 3. Create an index for faster context retrieval
create index if not exists memories_user_id_idx on public.memories (user_id);
create index if not exists memories_created_at_idx on public.memories (created_at desc);

-- 4. Set up Row Level Security (RLS)
-- For a bot, we often just want a service role key to bypass this.
-- If you use the anon key, you need to allow INSERT and SELECT.
alter table public.memories enable row level security;

-- Simple policy for the bot (using the anon key)
create policy "Bot can manage memories" 
on public.memories
for all
to anon, authenticated
using (true)
with check (true);
