-- Tier 1: Core Facts / Knowledge Table
create table if not exists public.facts (
  id bigint generated by default as identity primary key,
  user_id text not null,
  fact text not null,
  category text default 'general',
  embedding vector(1536), -- Matches OpenAI text-embedding-3-small
  metadata jsonb default '{}'::jsonb,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Index for user lookup
create index if not exists facts_user_id_idx on public.facts (user_id);

-- HNSW index for semantic similarity
create index if not exists facts_embedding_idx 
on public.facts 
using hnsw (embedding vector_cosine_ops);

-- RPC for semantic retrieval of facts
create or replace function match_facts (
  query_embedding vector(1536),
  match_threshold float,
  match_count int,
  p_user_id text
)
returns table (
  id bigint,
  fact text,
  category text,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    facts.id,
    facts.fact,
    facts.category,
    1 - (facts.embedding <=> query_embedding) as similarity
  from facts
  where facts.user_id = p_user_id
    and 1 - (facts.embedding <=> query_embedding) > match_threshold
  order by facts.embedding <=> query_embedding
  limit match_count;
end;
$$;
